version: '3.8'

services:

  web:
    build: ./
    command: uvicorn main:app --reload --workers 3 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/ledger_be
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://abram:ledger_b3_2022_db@db/ledger-db
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=abram
      - POSTGRES_PASSWORD=ledger_b3_2022_db
      - POSTGRES_DB=ledger-db

volumes:
  postgres_data:
