version: '3.8'

services:
  
  web:
    build: ./ledger_be
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn ledger.api:app --reload --workers 3 --host 0.0.0.0 --port 8000'
    volumes:
      - ./:/ledger_be
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://abram:ledger_b3_2022_db@db/ledger-db
      
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=abram
      - POSTGRES_PASSWORD=ledger_b3_2022_db
      - POSTGRES_DB=ledger-db

volumes:
  postgres_data:
