version: '3.8'

services:

  web:
    build: ./
    command: "uvicorn main:app --host='0.0.0.0' --port=8000 --reload"
    volumes:
      - ./:/ledger_be
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://abram:ledger_b3_2022_db@db/ledger-db
      - TEST_DATABASE_URL=postgresql://abram:ledger_b3_2022_testdb@test_db/ledger-testdb
    depends_on:
      - db
      - test_db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=abram
      - POSTGRES_PASSWORD=ledger_b3_2022_db
      - POSTGRES_DB=ledger-db
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:15.1-alpine
    volumes:
      - test_postgres_data:/var/lib/test_postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=abram
      - POSTGRES_PASSWORD=ledger_b3_2022_testdb
      - POSTGRES_DB=ledger-testdb
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  test_postgres_data:
